#lang racket
;; this file is automatically generated

(require "derived-core-properties.rkt"
"derived-binary-properties.rkt"
)
(provide (all-from-out "derived-core-properties.rkt"
"derived-binary-properties.rkt"
))